#define __STDC__ 1
#define __STDC_VERSION__ 199409L
#define __EDG__ 1
#define __EDG_VERSION__ 407
#define __EDG_SIZE_TYPE__ unsigned int
#define __EDG_PTRDIFF_TYPE__ int
#define __sizeof_int 4
#define __sizeof_long 4
#define __sizeof_ptr 4
#define __ARMCC_VERSION 5060960
#define __TARGET_CPU_CORTEX_M3 1
#define __TARGET_FPU_SOFTVFP 1
#define __EVAL 1
#define __UVISION_VERSION 535
#define _RTE_ 1
#define GD32F1x0 1
#define GD32F130_150 1
#define USE_STDPERIPH_DRIVER 1
#define __CC_ARM 1
#define __arm 1
#define __arm__ 1
#define __TARGET_ARCH_7_M 1
#define __TARGET_ARCH_ARM 0
#define __TARGET_ARCH_THUMB 4
#define __TARGET_ARCH_A64 0
#define __TARGET_ARCH_AARCH32 1
#define __TARGET_PROFILE_M 1
#define __TARGET_FEATURE_HALFWORD 1
#define __TARGET_FEATURE_THUMB 1
#define __TARGET_FEATURE_MULTIPLY 1
#define __TARGET_FEATURE_DOUBLEWORD 1
#define __TARGET_FEATURE_DIVIDE 1
#define __TARGET_FEATURE_UNALIGNED 1
#define __TARGET_FEATURE_CLZ 1
#define __TARGET_FEATURE_DMB 1
#define __TARGET_FEATURE_EXTENSION_REGISTER_COUNT 0
#define __APCS_INTERWORK 1
#define __thumb 1
#define __thumb__ 1
#define __t32__ 1
#define __OPTIMISE_SPACE 1
#define __OPTIMISE_LEVEL 0
#define __SOFTFP__ 1
